### ISSUE TITLE
"Value does not fall within the expected range" Argument Exception

### ISSUE THREAD

**Issue by FUNExtreme** [auth0/Auth0.Windows.UWP#6]
While working with the Auth0 UWP library I've bumped into the "Value does not fall within the expected range" exception quite a lot.
From my experience this seems to happen when the user interacts with the window before it is able to show the authentication window. For example by moving/resizing the parent window.
The exception occurs within the `WebAuthenticationBroker.AuthenticateAsync(WebAuthenticationOptions.None, startUri, endUri);`
call after calling `Auth0Client.LoginAsync();`

My guess is that the authentication broker fails to retreive the root window and causing this behaviour, but that is entirely speculative.

I've worked around this issue myself by wrapping the AuthenticateAsync method call with a try catch block and retrying 3 times before throwing an AuthenticationErrorException.
An ugly workaround, but it works and provides the user with more meaningful information than currently available.

I've not yet opened a pull request for this as I would prefer to hear your opinion first.

A URL to my fork: [Fork](https://github.com/FUNExtreme/Auth0.Windows.UWP)
And my workaround: [Workaround](https://github.com/FUNExtreme/Auth0.Windows.UWP/commit/b6e428d02afa1737934c9d876d0c0438f0a5c812)

**Comment by jerriep** [comment]
Hi @FUNExtreme I am trying to replicate your issue, but I am unable to. 

If I understand correctly you are clicking on the button which will show the Auth0 auth dialog, but before it has time to appear on the screen you move the parent window. Then when the auth dialog tries to display it throws an error. Is that correct?

**Comment by FUNExtreme** [comment]
That's the closest I ever came to replicating the issue. I've yet to find a 100% reproducable scenario, making it that much more annoying.
I've since moved on to a different project so I'm not sure if I'll be of much use to you anymore.
