### ISSUE TITLE
exception when login through twitter 

### ISSUE THREAD

**Issue by Amialc** [auth0/Auth0.Windows.UWP#7]
When i'm trying login with twitter i've get exception because `result` variable is empty.
![image](https://cloud.githubusercontent.com/assets/1114365/17980772/7fd50df0-6b09-11e6-8103-804fc11aeb49.png)

**Comment by jerriep** [comment]
This library is not supported anymore. Please use the Auth0 OIDC Client as described in https://auth0.com/docs/quickstart/native/windows-uwp-csharp
