### ISSUE TITLE
Auth0AccessToken is invalid

### ISSUE THREAD

**Issue by mikecousins** [auth0/Auth0.Windows.UWP#9]
I have talked to support and the token that I'm getting after logging in is not correct.

For instance at one point my token was "7oH99r52p3C1N5LT" and support said it should be longer and start with "eyJ...".

This is the code that results in `token` being set to an invalid value:

```
var auth0 = new Auth0Client("*****", "******");
var user = await auth0.LoginAsync();
var token = auth0.CurrentUser.Auth0AccessToken;
```

**Comment by jerriep** [comment]
This library is not supported anymore. Please use the Auth0 OIDC Client as described in https://auth0.com/docs/quickstart/native/windows-uwp-csharp
